artifact_location: file:c:/Users/erick/documents/Full_Stack/python/machine-learning/mlops/tracking/tracking/experiment_ml/736316104182322711
creation_time: 1748287835433
experiment_id: '736316104182322711'
last_update_time: 1748287835433
lifecycle_stage: active
name: iris_experiment_ml_local
