artifact_location: file:c:/Users/erick/documents/Full_Stack/python/machine-learning/mlops/tracking/tracking/experiment_ml/0
creation_time: 1748287807934
experiment_id: '0'
last_update_time: 1748287807934
lifecycle_stage: active
name: Default
